name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Test with dotnet test
          run: dotnet test "SampleProject.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-result.xml"
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v3
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: "test-result.xml"
          # Use always() to always run this step to publish test results when there are test failures
            #if: ${{ always() }}
        - name: Parse_Results
          env:
                NewTestCycle: 55152
                qTestProject: 9655
                qTestPULSEURL: https://pulse-13.qtestnet.com/webhook/9c276f29-0b44-43bd-9363-b4bc436f57c5
          run: |
                for file in $( find -type f -name "*.xml")
                do
                  echo -e "Working on file -----------------------------------> $file"
                  Parser_Response=$(curl --request POST $qTestPULSEURL -d "projectId=$qTestProject" -d "testcycle=$NewTestCycle" -d "result=$(echo $(cat $file) | basenc --base64url | tr -d \\n)" )             
                done
                curl -L -X PUT https://test-reports.behave.pro/REST/1.0/bdd/report \

        - name: upload behave pro results in jira
          run: |
                curl -L -X PUT https://test-reports.behave.pro/REST/1.0/bdd/report \
                -H "X-API-KEY: OWMzODAyYzctMDM3Mi00NDRkLTgwODgtYjA2NGM4ZTFhZDljLlpEbmZjZmFXbmVxalZZTERkaHQ4 \
                -H "X-COMMIT-ID: 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 \
                -H "X-BUILD-ID: $GITHUB_RUN_ID" \
                -H "X-BUILD-URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" 

                
           
           
            
